/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagementsystem;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.sql.*;
import project.*;

/**
 *
 * 
 */
public class CheckInCustomer extends javax.swing.JFrame {

    /**
     * Creates new form CheckInCustomer
     */
    public CheckInCustomer() {
        initComponents();
        checkdate.setEditable(false);
        roomPrice.setEditable(false);
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd"); //format we want for the date
        Calendar cal =  Calendar.getInstance(); // gets calender using current date
        checkdate.setText(myFormat.format(cal.getTime())); //returns date object
    }
    String bedType ;
    String roomType;
    String roomNo;
    String price;
    
    public void roomDetails() //method to enter room details
    {
        roomNumber.removeAllItems(); //changes according to the bed type when we clear
        roomPrice.setText("");
        bedType = (String)beds.getSelectedItem();
        roomType = (String)type.getSelectedItem();
        try
        {
            ResultSet rs = Select.getData("select * from room where bedType ='"+bedType+"'and roomType ='"+roomType+"'and status = 'Not Booked'");
        while(rs.next())
        {
            roomNumber.addItem(rs.getString(1));
        }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        customername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        customerNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cusnat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cusgender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cusemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cusid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cusaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkdate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        beds = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        roomNumber = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        roomPrice = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Customer Check In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 330, -1));

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1139, 9, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 116, 37, -1));

        customername.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(customername, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, 350, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 201, 109, -1));

        customerNumber.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        customerNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNumberActionPerformed(evt);
            }
        });
        getContentPane().add(customerNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 235, 350, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nationality");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 288, 92, -1));

        cusnat.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(cusnat, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 322, 350, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 371, 62, -1));

        cusgender.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        cusgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        cusgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusgenderActionPerformed(evt);
            }
        });
        getContentPane().add(cusgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 399, 350, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 463, 84, -1));

        cusemail.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(cusemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 505, 350, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 116, 37, -1));

        cusid.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(cusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 150, 350, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 201, 54, -1));

        cusaddress.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(cusaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 235, 350, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Check-In-Date(TODAY)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 288, -1, -1));

        checkdate.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(checkdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 322, 350, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bed");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 116, 43, -1));

        beds.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        beds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Suite" }));
        beds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedsActionPerformed(evt);
            }
        });
        getContentPane().add(beds, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 150, 350, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RoomType");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 201, -1, -1));

        type.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 235, 350, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Room Number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 288, -1, -1));

        roomNumber.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        roomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberActionPerformed(evt);
            }
        });
        getContentPane().add(roomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 322, 350, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 371, 43, -1));

        roomPrice.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(roomPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 399, 350, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton2.setText("ASSIGN ROOM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 453, 144, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 453, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sorrisbig2.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, -50, 1490, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNumberActionPerformed

    private void cusgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusgenderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CheckInCustomer().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedsActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_bedsActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_typeActionPerformed

    private void roomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberActionPerformed
        // TODO add your handling code here:
        roomNo = (String)roomNumber.getSelectedItem(); // when room number changes , price must also change
        try
        {
            ResultSet rs = Select.getData("select * from room where roomNo ='"+roomNo+"'");
            while(rs.next())
            {
                roomPrice.setText(rs.getString(4));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_roomNumberActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int id = 1;
        String name = customername.getText();
        String phoneNumber = customerNumber.getText();
        String nationality = cusnat.getText();
        String gender = (String)cusgender.getSelectedItem();
        String email = cusemail.getText();
        String idproof = cusid.getText();
        String  address = cusaddress.getText();
        String  checkIn = checkdate.getText();
        String bedType = (String)beds.getSelectedItem();
        String roomType = (String)type.getSelectedItem();
        String roomNo = (String)roomNumber.getSelectedItem();
        String price = roomPrice.getText();
        String Query ="select max(id)from customers";
                        
        try
        { 
            ResultSet rs = Select.getData(Query);
            while(rs.next()) // no record means the while will not run
                id = rs.getInt(1);
            id = id+1;
             
            
            if(!price.equals(""))
            {
                Query = "update room set status = 'Booked' where roomNo = '"+roomNo+"'";
                InsertUpdateDelete.setData(Query, ""); // message is not visible
                Query = "insert into customers(id,name,phoneNumber,nationality,gender,email,idproof,address,checkIn,roomNo,bedType,roomType,pricePerday) values("+id+",'"+name+"','"+phoneNumber+"','"+nationality+"','"+gender+"','"+email+"','"+idproof+"','"+address+"','"+checkIn+"','"+roomNo+"','"+bedType+"','"+roomType+"','"+price+"')";
                InsertUpdateDelete.setData(Query,"Customer booking succesfull" );
                setVisible(false);
                new CheckInCustomer().setVisible(true);
               
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckInCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckInCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckInCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckInCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckInCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> beds;
    private javax.swing.JTextField checkdate;
    private javax.swing.JTextField cusaddress;
    private javax.swing.JTextField cusemail;
    private javax.swing.JComboBox<String> cusgender;
    private javax.swing.JTextField cusid;
    private javax.swing.JTextField cusnat;
    private javax.swing.JTextField customerNumber;
    private javax.swing.JTextField customername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> roomNumber;
    private javax.swing.JTextField roomPrice;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
