     
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagementsystem;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 import project.*;

/**
 *
 * 
 */
  
public class CustomerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckOut
     */
    public CustomerCheckOut() { //means the fiedls cannot be edited
        initComponents();
        cname.setEditable(false);
        checkdate.setEditable(false);
        checkout.setEditable(false);
        cphone.setEditable(false);
        roomPrice.setEditable(false);
        days.setEditable(false);
        totalcost.setEditable(false);
        cemail.setEditable(false);
    }
    int id= 0;
    String Query;
    String roomType;
    String bedType;
    String roomNo;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        roomNumber = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        checkdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkout = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cphone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        roomPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        days = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalcost = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cemail = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("CUSTOMER CHECK OUT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, 339, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1153, 19, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 59, 106, -1));

        roomNumber.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(roomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 56, 126, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 56, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone Number", "Nationality", "Gender", "Email", "ID Proof", "Address", "CheckIn Date", "Room Number", "Bed Type", "Room Type", "Price per day"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 322, 1230, 301));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 133, -1));

        cname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 129, 254, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check In-Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 101, 113, -1));

        checkdate.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        checkdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkdateActionPerformed(evt);
            }
        });
        getContentPane().add(checkdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 129, 250, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Check Out Date(Today)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 101, 136, -1));

        checkout.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 129, 250, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 101, 93, -1));

        cphone.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(cphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 129, 250, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price Per Day");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 177, 91, -1));

        roomPrice.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(roomPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 211, 254, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Days Stayed");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 177, 79, -1));

        days.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 211, 250, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Cost");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 177, 122, -1));

        totalcost.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        totalcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalcostActionPerformed(evt);
            }
        });
        getContentPane().add(totalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 211, 250, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 177, 95, -1));

        cemail.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        getContentPane().add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 211, 250, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton3.setText("CHECK OUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 278, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 278, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sorrisbig2.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkdateActionPerformed

    private void totalcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalcostActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs = Select.getData("select * from customers where checkOut is NULL");
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        try
        {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13)});
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
                
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String roomNo = roomNumber.getText();
        try
        {
            ResultSet rs = Select.getData("select * from customers where roomNo ='"+roomNo+"'and checkout is NULL ");
            if(rs.next())
            {
                roomNumber.setEditable(false);// means a room exits
                id =rs.getInt(1);
                cname.setText(rs.getString(2));
                checkdate.setText(rs.getString(9));
                cphone.setText(rs.getString(3));
                roomPrice.setText(rs.getString(13));
                
                SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd"); // format for the date
                Calendar cal = Calendar.getInstance(); // gets the current date
                checkout.setText(myFormat.format(cal.getTime()));
                String dateBeforeString = rs.getString(9);
                java.util.Date dateBefore = myFormat.parse(dateBeforeString);
                String dateAfterString = myFormat.format(cal.getTime()); // gets todays date
                java.util.Date dateAfter = myFormat.parse(dateAfterString);
                long difference =  dateAfter.getTime() - dateBefore.getTime(); // long datatype for difference to find number of days stayed
                int numberOfDays = (int) (difference/(1000*60*60*24)); // miliseconds
                if(numberOfDays==0)
                    numberOfDays =1; // it will calculate the 0 days
                days.setText(String.valueOf(numberOfDays)); //sets the value of days stayed
                float price = Float.parseFloat(roomPrice.getText());
                totalcost.setText(String.valueOf(numberOfDays*price)); //calculate the total cost
                cemail.setText(rs.getString(6));
                roomType = rs.getString(12);
                bedType = rs.getString(11);
               
                
            }
            else
                JOptionPane.showMessageDialog(null, "Room does not exist or Room has not been booked");
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String  name = cname.getText();
        String phone = cphone.getText();
        String email = cemail.getText();
        
        String checkOut = checkout.getText();
        String numberOfDays = days.getText();
        String totalAmount = totalcost.getText();
        roomNo =roomNumber.getText();
        
        Query= "update customers set numberOfDays ='"+numberOfDays+"',totalAmount ='"+totalAmount+"',checkOut='"+checkOut+"'where id ='"+id+"'";//updates table
        InsertUpdateDelete.setData(Query,""); 
        Query = "update room set status ='Not Booked' where roomNo = '"+roomNo+"' ";
        InsertUpdateDelete.setData(Query, ""); // no need for message
        String path ="C:\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        
        try
        {
            PdfWriter.getInstance(doc, new FileOutputStream(path +""+id+ ".pdf"));
           doc.open();
           Paragraph paragraph1 = new Paragraph("                                                  Hotel Management System \n");
           doc.add(paragraph1);
           Paragraph paragraph2 = new Paragraph("**************************************************************************************************************");
           doc.add(paragraph2);
           Paragraph paragraph3 = new Paragraph("\tCost ID: "+id+"\nCustomer Details: \nName: "+name+"\nPhone Number: "+phone+"\nEmail: "+email+"\n ");                                                                                       
           doc.add(paragraph3);
           doc.add(paragraph2);
           Paragraph paragraph4 = new Paragraph("\tRoom Details: \nRoom Number: "+roomNumber.getText()+"\nType: "+roomType+"\nBed: "+bedType+"\nCost Per Day : "+roomPrice.getText()+" ");                                                                                       
           doc.add(paragraph4);
           doc.add(paragraph2);
           PdfPTable tb1 = new PdfPTable(4) ;
           tb1.addCell("Check In Date: "+checkdate.getText());
           tb1.addCell("Check Out Date: "+checkOut);
           tb1.addCell("Number of Days stayed: "+numberOfDays);
           tb1.addCell("Total Amount: "+totalAmount);
           doc.add(tb1);
           doc.add(paragraph2);
           Paragraph paragraph5 = new Paragraph("We hope you enjoyed your stay.Please visit again! \n");
           doc.add(paragraph5);
           
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
         int a = JOptionPane.showConfirmDialog(null, "Do you want to see the invoice? ","Select",JOptionPane.YES_NO_OPTION);
         if(a==0) // if yes is selected
         {
             try
             {
                 if((new File("C:\\"+id+".pdf")) .exists())
                 {
                   Process p = Runtime
                           .getRuntime()
                           .exec("rundll32 url.dll,FileProtocolHandler D:\\"+id+".pdf");
                           
                 }
                 else
                     System.out.println("File Does Not exist");
                        
             }
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(null, e);
             }
         }
          setVisible(false);
          new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cemail;
    private javax.swing.JTextField checkdate;
    private javax.swing.JTextField checkout;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cphone;
    private javax.swing.JTextField days;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField roomNumber;
    private javax.swing.JTextField roomPrice;
    private javax.swing.JTextField totalcost;
    // End of variables declaration//GEN-END:variables
}
